package com.cmall.dborm.txmapper.newscenter;

import com.cmall.dborm.txmodel.newscenter.NcPost;
import com.cmall.dborm.txmodel.newscenter.NcPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NcPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int countByExample(NcPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int deleteByExample(NcPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int insert(NcPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int insertSelective(NcPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    List<NcPost> selectByExample(NcPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    NcPost selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NcPost record, @Param("example") NcPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NcPost record, @Param("example") NcPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NcPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NcPost record);
}