package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcActiveLog;
import com.cmall.dborm.txmodel.groupcenter.GcActiveLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcActiveLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int countByExample(GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int deleteByExample(GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int insert(GcActiveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int insertSelective(GcActiveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    List<GcActiveLog> selectByExampleWithBLOBs(GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    List<GcActiveLog> selectByExample(GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    GcActiveLog selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcActiveLog record, @Param("example") GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") GcActiveLog record, @Param("example") GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcActiveLog record, @Param("example") GcActiveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcActiveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(GcActiveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_active_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcActiveLog record);
}