package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcMemberRelation;
import com.cmall.dborm.txmodel.groupcenter.GcMemberRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcMemberRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int countByExample(GcMemberRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int deleteByExample(GcMemberRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int insert(GcMemberRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int insertSelective(GcMemberRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    List<GcMemberRelation> selectByExample(GcMemberRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    GcMemberRelation selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcMemberRelation record, @Param("example") GcMemberRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcMemberRelation record, @Param("example") GcMemberRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcMemberRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcMemberRelation record);
}