package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcMemberBank;
import com.cmall.dborm.txmodel.groupcenter.GcMemberBankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcMemberBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int countByExample(GcMemberBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int deleteByExample(GcMemberBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int insert(GcMemberBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int insertSelective(GcMemberBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    List<GcMemberBank> selectByExample(GcMemberBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    GcMemberBank selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcMemberBank record, @Param("example") GcMemberBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcMemberBank record, @Param("example") GcMemberBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcMemberBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_member_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcMemberBank record);
}