package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcPayOrderInfo;
import com.cmall.dborm.txmodel.groupcenter.GcPayOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcPayOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int countByExample(GcPayOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int deleteByExample(GcPayOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int insert(GcPayOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int insertSelective(GcPayOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    List<GcPayOrderInfo> selectByExample(GcPayOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    GcPayOrderInfo selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcPayOrderInfo record, @Param("example") GcPayOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcPayOrderInfo record, @Param("example") GcPayOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcPayOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_pay_order_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcPayOrderInfo record);
}