package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcReckonOrderInfo;
import com.cmall.dborm.txmodel.groupcenter.GcReckonOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcReckonOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int countByExample(GcReckonOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int deleteByExample(GcReckonOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int insert(GcReckonOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int insertSelective(GcReckonOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    List<GcReckonOrderInfo> selectByExample(GcReckonOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    GcReckonOrderInfo selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcReckonOrderInfo record, @Param("example") GcReckonOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcReckonOrderInfo record, @Param("example") GcReckonOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcReckonOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcReckonOrderInfo record);
}