package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcReckonOrderDetail;
import com.cmall.dborm.txmodel.groupcenter.GcReckonOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcReckonOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int countByExample(GcReckonOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int deleteByExample(GcReckonOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int insert(GcReckonOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(GcReckonOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    List<GcReckonOrderDetail> selectByExample(GcReckonOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    GcReckonOrderDetail selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcReckonOrderDetail record, @Param("example") GcReckonOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcReckonOrderDetail record, @Param("example") GcReckonOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcReckonOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcReckonOrderDetail record);
}