package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcReckonLog;
import com.cmall.dborm.txmodel.groupcenter.GcReckonLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcReckonLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int countByExample(GcReckonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int deleteByExample(GcReckonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int insert(GcReckonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int insertSelective(GcReckonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    List<GcReckonLog> selectByExample(GcReckonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    GcReckonLog selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcReckonLog record, @Param("example") GcReckonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcReckonLog record, @Param("example") GcReckonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcReckonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcReckonLog record);
}