package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcReckonOrderReturnDetail;
import com.cmall.dborm.txmodel.groupcenter.GcReckonOrderReturnDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcReckonOrderReturnDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int countByExample(GcReckonOrderReturnDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int deleteByExample(GcReckonOrderReturnDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int insert(GcReckonOrderReturnDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int insertSelective(GcReckonOrderReturnDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    List<GcReckonOrderReturnDetail> selectByExample(GcReckonOrderReturnDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    GcReckonOrderReturnDetail selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcReckonOrderReturnDetail record, @Param("example") GcReckonOrderReturnDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcReckonOrderReturnDetail record, @Param("example") GcReckonOrderReturnDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcReckonOrderReturnDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_reckon_order_return_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcReckonOrderReturnDetail record);
}