package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcTraderAccountLog;
import com.cmall.dborm.txmodel.groupcenter.GcTraderAccountLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcTraderAccountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int countByExample(GcTraderAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int deleteByExample(GcTraderAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int insert(GcTraderAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int insertSelective(GcTraderAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    List<GcTraderAccountLog> selectByExample(GcTraderAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    GcTraderAccountLog selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcTraderAccountLog record, @Param("example") GcTraderAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcTraderAccountLog record, @Param("example") GcTraderAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcTraderAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_account_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcTraderAccountLog record);
}