package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcTraderWalletChangeLog;
import com.cmall.dborm.txmodel.groupcenter.GcTraderWalletChangeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcTraderWalletChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int countByExample(GcTraderWalletChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int deleteByExample(GcTraderWalletChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int insert(GcTraderWalletChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int insertSelective(GcTraderWalletChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    List<GcTraderWalletChangeLog> selectByExample(GcTraderWalletChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    GcTraderWalletChangeLog selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcTraderWalletChangeLog record, @Param("example") GcTraderWalletChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcTraderWalletChangeLog record, @Param("example") GcTraderWalletChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcTraderWalletChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet_change_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcTraderWalletChangeLog record);
}