package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcTraderWallet;
import com.cmall.dborm.txmodel.groupcenter.GcTraderWalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcTraderWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int countByExample(GcTraderWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int deleteByExample(GcTraderWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int insert(GcTraderWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int insertSelective(GcTraderWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    List<GcTraderWallet> selectByExample(GcTraderWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    GcTraderWallet selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcTraderWallet record, @Param("example") GcTraderWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcTraderWallet record, @Param("example") GcTraderWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcTraderWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_trader_wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcTraderWallet record);
}