package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcVpayOrder;
import com.cmall.dborm.txmodel.groupcenter.GcVpayOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcVpayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int countByExample(GcVpayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int deleteByExample(GcVpayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int insert(GcVpayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int insertSelective(GcVpayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    List<GcVpayOrder> selectByExample(GcVpayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    GcVpayOrder selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcVpayOrder record, @Param("example") GcVpayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcVpayOrder record, @Param("example") GcVpayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcVpayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_vpay_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcVpayOrder record);
}