package com.cmall.dborm.txmapper.groupcenter;

import com.cmall.dborm.txmodel.groupcenter.GcWalletWithdrawLog;
import com.cmall.dborm.txmodel.groupcenter.GcWalletWithdrawLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcWalletWithdrawLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int countByExample(GcWalletWithdrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int deleteByExample(GcWalletWithdrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int insert(GcWalletWithdrawLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int insertSelective(GcWalletWithdrawLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    List<GcWalletWithdrawLog> selectByExample(GcWalletWithdrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    GcWalletWithdrawLog selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GcWalletWithdrawLog record, @Param("example") GcWalletWithdrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GcWalletWithdrawLog record, @Param("example") GcWalletWithdrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GcWalletWithdrawLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_wallet_withdraw_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GcWalletWithdrawLog record);
}