package com.cmall.dborm.txmapper.membercenter;

import com.cmall.dborm.txmodel.membercenter.McExtendInfoStar;
import com.cmall.dborm.txmodel.membercenter.McExtendInfoStarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface McExtendInfoStarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int countByExample(McExtendInfoStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int deleteByExample(McExtendInfoStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int insert(McExtendInfoStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int insertSelective(McExtendInfoStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    List<McExtendInfoStar> selectByExample(McExtendInfoStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    McExtendInfoStar selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") McExtendInfoStar record, @Param("example") McExtendInfoStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") McExtendInfoStar record, @Param("example") McExtendInfoStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(McExtendInfoStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_extend_info_star
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(McExtendInfoStar record);
}