package com.cmall.dborm.txmapper.membercenter;

import com.cmall.dborm.txmodel.membercenter.McLoginInfo;
import com.cmall.dborm.txmodel.membercenter.McLoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface McLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int countByExample(McLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int deleteByExample(McLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int insert(McLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int insertSelective(McLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    List<McLoginInfo> selectByExample(McLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    McLoginInfo selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") McLoginInfo record, @Param("example") McLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") McLoginInfo record, @Param("example") McLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(McLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_login_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(McLoginInfo record);
}