package com.cmall.dborm.txmodel;

import java.util.ArrayList;
import java.util.List;

public class HcMatchingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public HcMatchingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZidIsNull() {
            addCriterion("zid is null");
            return (Criteria) this;
        }

        public Criteria andZidIsNotNull() {
            addCriterion("zid is not null");
            return (Criteria) this;
        }

        public Criteria andZidEqualTo(Integer value) {
            addCriterion("zid =", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotEqualTo(Integer value) {
            addCriterion("zid <>", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThan(Integer value) {
            addCriterion("zid >", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThanOrEqualTo(Integer value) {
            addCriterion("zid >=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThan(Integer value) {
            addCriterion("zid <", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThanOrEqualTo(Integer value) {
            addCriterion("zid <=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidIn(List<Integer> values) {
            addCriterion("zid in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotIn(List<Integer> values) {
            addCriterion("zid not in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidBetween(Integer value1, Integer value2) {
            addCriterion("zid between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotBetween(Integer value1, Integer value2) {
            addCriterion("zid not between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderId like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderId not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMIsNull() {
            addCriterion("member_code_m is null");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMIsNotNull() {
            addCriterion("member_code_m is not null");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMEqualTo(String value) {
            addCriterion("member_code_m =", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMNotEqualTo(String value) {
            addCriterion("member_code_m <>", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMGreaterThan(String value) {
            addCriterion("member_code_m >", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMGreaterThanOrEqualTo(String value) {
            addCriterion("member_code_m >=", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMLessThan(String value) {
            addCriterion("member_code_m <", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMLessThanOrEqualTo(String value) {
            addCriterion("member_code_m <=", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMLike(String value) {
            addCriterion("member_code_m like", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMNotLike(String value) {
            addCriterion("member_code_m not like", value, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMIn(List<String> values) {
            addCriterion("member_code_m in", values, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMNotIn(List<String> values) {
            addCriterion("member_code_m not in", values, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMBetween(String value1, String value2) {
            addCriterion("member_code_m between", value1, value2, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeMNotBetween(String value1, String value2) {
            addCriterion("member_code_m not between", value1, value2, "memberCodeM");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGIsNull() {
            addCriterion("member_code_g is null");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGIsNotNull() {
            addCriterion("member_code_g is not null");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGEqualTo(String value) {
            addCriterion("member_code_g =", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGNotEqualTo(String value) {
            addCriterion("member_code_g <>", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGGreaterThan(String value) {
            addCriterion("member_code_g >", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGGreaterThanOrEqualTo(String value) {
            addCriterion("member_code_g >=", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGLessThan(String value) {
            addCriterion("member_code_g <", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGLessThanOrEqualTo(String value) {
            addCriterion("member_code_g <=", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGLike(String value) {
            addCriterion("member_code_g like", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGNotLike(String value) {
            addCriterion("member_code_g not like", value, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGIn(List<String> values) {
            addCriterion("member_code_g in", values, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGNotIn(List<String> values) {
            addCriterion("member_code_g not in", values, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGBetween(String value1, String value2) {
            addCriterion("member_code_g between", value1, value2, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMemberCodeGNotBetween(String value1, String value2) {
            addCriterion("member_code_g not between", value1, value2, "memberCodeG");
            return (Criteria) this;
        }

        public Criteria andMobileMIsNull() {
            addCriterion("mobile_m is null");
            return (Criteria) this;
        }

        public Criteria andMobileMIsNotNull() {
            addCriterion("mobile_m is not null");
            return (Criteria) this;
        }

        public Criteria andMobileMEqualTo(String value) {
            addCriterion("mobile_m =", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMNotEqualTo(String value) {
            addCriterion("mobile_m <>", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMGreaterThan(String value) {
            addCriterion("mobile_m >", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_m >=", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMLessThan(String value) {
            addCriterion("mobile_m <", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMLessThanOrEqualTo(String value) {
            addCriterion("mobile_m <=", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMLike(String value) {
            addCriterion("mobile_m like", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMNotLike(String value) {
            addCriterion("mobile_m not like", value, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMIn(List<String> values) {
            addCriterion("mobile_m in", values, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMNotIn(List<String> values) {
            addCriterion("mobile_m not in", values, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMBetween(String value1, String value2) {
            addCriterion("mobile_m between", value1, value2, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileMNotBetween(String value1, String value2) {
            addCriterion("mobile_m not between", value1, value2, "mobileM");
            return (Criteria) this;
        }

        public Criteria andMobileGIsNull() {
            addCriterion("mobile_g is null");
            return (Criteria) this;
        }

        public Criteria andMobileGIsNotNull() {
            addCriterion("mobile_g is not null");
            return (Criteria) this;
        }

        public Criteria andMobileGEqualTo(String value) {
            addCriterion("mobile_g =", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGNotEqualTo(String value) {
            addCriterion("mobile_g <>", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGGreaterThan(String value) {
            addCriterion("mobile_g >", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_g >=", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGLessThan(String value) {
            addCriterion("mobile_g <", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGLessThanOrEqualTo(String value) {
            addCriterion("mobile_g <=", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGLike(String value) {
            addCriterion("mobile_g like", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGNotLike(String value) {
            addCriterion("mobile_g not like", value, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGIn(List<String> values) {
            addCriterion("mobile_g in", values, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGNotIn(List<String> values) {
            addCriterion("mobile_g not in", values, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGBetween(String value1, String value2) {
            addCriterion("mobile_g between", value1, value2, "mobileG");
            return (Criteria) this;
        }

        public Criteria andMobileGNotBetween(String value1, String value2) {
            addCriterion("mobile_g not between", value1, value2, "mobileG");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hc_matching
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hc_matching
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}