package com.cmall.dborm.txmodel;

import java.util.ArrayList;
import java.util.List;

public class LcProductinfoBatchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public LcProductinfoBatchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZidIsNull() {
            addCriterion("zid is null");
            return (Criteria) this;
        }

        public Criteria andZidIsNotNull() {
            addCriterion("zid is not null");
            return (Criteria) this;
        }

        public Criteria andZidEqualTo(Integer value) {
            addCriterion("zid =", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotEqualTo(Integer value) {
            addCriterion("zid <>", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThan(Integer value) {
            addCriterion("zid >", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThanOrEqualTo(Integer value) {
            addCriterion("zid >=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThan(Integer value) {
            addCriterion("zid <", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThanOrEqualTo(Integer value) {
            addCriterion("zid <=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidIn(List<Integer> values) {
            addCriterion("zid in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotIn(List<Integer> values) {
            addCriterion("zid not in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidBetween(Integer value1, Integer value2) {
            addCriterion("zid between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotBetween(Integer value1, Integer value2) {
            addCriterion("zid not between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusIsNull() {
            addCriterion("update_status is null");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusIsNotNull() {
            addCriterion("update_status is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusEqualTo(String value) {
            addCriterion("update_status =", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotEqualTo(String value) {
            addCriterion("update_status <>", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusGreaterThan(String value) {
            addCriterion("update_status >", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusGreaterThanOrEqualTo(String value) {
            addCriterion("update_status >=", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusLessThan(String value) {
            addCriterion("update_status <", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusLessThanOrEqualTo(String value) {
            addCriterion("update_status <=", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusLike(String value) {
            addCriterion("update_status like", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotLike(String value) {
            addCriterion("update_status not like", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusIn(List<String> values) {
            addCriterion("update_status in", values, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotIn(List<String> values) {
            addCriterion("update_status not in", values, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusBetween(String value1, String value2) {
            addCriterion("update_status between", value1, value2, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotBetween(String value1, String value2) {
            addCriterion("update_status not between", value1, value2, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductShortnameIsNull() {
            addCriterion("product_shortname is null");
            return (Criteria) this;
        }

        public Criteria andProductShortnameIsNotNull() {
            addCriterion("product_shortname is not null");
            return (Criteria) this;
        }

        public Criteria andProductShortnameEqualTo(String value) {
            addCriterion("product_shortname =", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameNotEqualTo(String value) {
            addCriterion("product_shortname <>", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameGreaterThan(String value) {
            addCriterion("product_shortname >", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameGreaterThanOrEqualTo(String value) {
            addCriterion("product_shortname >=", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameLessThan(String value) {
            addCriterion("product_shortname <", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameLessThanOrEqualTo(String value) {
            addCriterion("product_shortname <=", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameLike(String value) {
            addCriterion("product_shortname like", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameNotLike(String value) {
            addCriterion("product_shortname not like", value, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameIn(List<String> values) {
            addCriterion("product_shortname in", values, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameNotIn(List<String> values) {
            addCriterion("product_shortname not in", values, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameBetween(String value1, String value2) {
            addCriterion("product_shortname between", value1, value2, "productShortname");
            return (Criteria) this;
        }

        public Criteria andProductShortnameNotBetween(String value1, String value2) {
            addCriterion("product_shortname not between", value1, value2, "productShortname");
            return (Criteria) this;
        }

        public Criteria andBrandCodeIsNull() {
            addCriterion("brand_code is null");
            return (Criteria) this;
        }

        public Criteria andBrandCodeIsNotNull() {
            addCriterion("brand_code is not null");
            return (Criteria) this;
        }

        public Criteria andBrandCodeEqualTo(String value) {
            addCriterion("brand_code =", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotEqualTo(String value) {
            addCriterion("brand_code <>", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeGreaterThan(String value) {
            addCriterion("brand_code >", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeGreaterThanOrEqualTo(String value) {
            addCriterion("brand_code >=", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeLessThan(String value) {
            addCriterion("brand_code <", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeLessThanOrEqualTo(String value) {
            addCriterion("brand_code <=", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeLike(String value) {
            addCriterion("brand_code like", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotLike(String value) {
            addCriterion("brand_code not like", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeIn(List<String> values) {
            addCriterion("brand_code in", values, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotIn(List<String> values) {
            addCriterion("brand_code not in", values, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeBetween(String value1, String value2) {
            addCriterion("brand_code between", value1, value2, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotBetween(String value1, String value2) {
            addCriterion("brand_code not between", value1, value2, "brandCode");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("category_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("category_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("category_name =", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("category_name <>", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("category_name >", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("category_name >=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("category_name <", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("category_name <=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("category_name like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("category_name not like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIn(List<String> values) {
            addCriterion("category_name in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotIn(List<String> values) {
            addCriterion("category_name not in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("category_name between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("category_name not between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstIsNull() {
            addCriterion("category_name_first is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstIsNotNull() {
            addCriterion("category_name_first is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstEqualTo(String value) {
            addCriterion("category_name_first =", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstNotEqualTo(String value) {
            addCriterion("category_name_first <>", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstGreaterThan(String value) {
            addCriterion("category_name_first >", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstGreaterThanOrEqualTo(String value) {
            addCriterion("category_name_first >=", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstLessThan(String value) {
            addCriterion("category_name_first <", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstLessThanOrEqualTo(String value) {
            addCriterion("category_name_first <=", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstLike(String value) {
            addCriterion("category_name_first like", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstNotLike(String value) {
            addCriterion("category_name_first not like", value, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstIn(List<String> values) {
            addCriterion("category_name_first in", values, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstNotIn(List<String> values) {
            addCriterion("category_name_first not in", values, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstBetween(String value1, String value2) {
            addCriterion("category_name_first between", value1, value2, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameFirstNotBetween(String value1, String value2) {
            addCriterion("category_name_first not between", value1, value2, "categoryNameFirst");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondIsNull() {
            addCriterion("category_name_second is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondIsNotNull() {
            addCriterion("category_name_second is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondEqualTo(String value) {
            addCriterion("category_name_second =", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondNotEqualTo(String value) {
            addCriterion("category_name_second <>", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondGreaterThan(String value) {
            addCriterion("category_name_second >", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondGreaterThanOrEqualTo(String value) {
            addCriterion("category_name_second >=", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondLessThan(String value) {
            addCriterion("category_name_second <", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondLessThanOrEqualTo(String value) {
            addCriterion("category_name_second <=", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondLike(String value) {
            addCriterion("category_name_second like", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondNotLike(String value) {
            addCriterion("category_name_second not like", value, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondIn(List<String> values) {
            addCriterion("category_name_second in", values, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondNotIn(List<String> values) {
            addCriterion("category_name_second not in", values, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondBetween(String value1, String value2) {
            addCriterion("category_name_second between", value1, value2, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameSecondNotBetween(String value1, String value2) {
            addCriterion("category_name_second not between", value1, value2, "categoryNameSecond");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdIsNull() {
            addCriterion("category_name_third is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdIsNotNull() {
            addCriterion("category_name_third is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdEqualTo(String value) {
            addCriterion("category_name_third =", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdNotEqualTo(String value) {
            addCriterion("category_name_third <>", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdGreaterThan(String value) {
            addCriterion("category_name_third >", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdGreaterThanOrEqualTo(String value) {
            addCriterion("category_name_third >=", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdLessThan(String value) {
            addCriterion("category_name_third <", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdLessThanOrEqualTo(String value) {
            addCriterion("category_name_third <=", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdLike(String value) {
            addCriterion("category_name_third like", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdNotLike(String value) {
            addCriterion("category_name_third not like", value, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdIn(List<String> values) {
            addCriterion("category_name_third in", values, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdNotIn(List<String> values) {
            addCriterion("category_name_third not in", values, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdBetween(String value1, String value2) {
            addCriterion("category_name_third between", value1, value2, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andCategoryNameThirdNotBetween(String value1, String value2) {
            addCriterion("category_name_third not between", value1, value2, "categoryNameThird");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNull() {
            addCriterion("properties is null");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNotNull() {
            addCriterion("properties is not null");
            return (Criteria) this;
        }

        public Criteria andPropertiesEqualTo(String value) {
            addCriterion("properties =", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotEqualTo(String value) {
            addCriterion("properties <>", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThan(String value) {
            addCriterion("properties >", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("properties >=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThan(String value) {
            addCriterion("properties <", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThanOrEqualTo(String value) {
            addCriterion("properties <=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLike(String value) {
            addCriterion("properties like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotLike(String value) {
            addCriterion("properties not like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesIn(List<String> values) {
            addCriterion("properties in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotIn(List<String> values) {
            addCriterion("properties not in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesBetween(String value1, String value2) {
            addCriterion("properties between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotBetween(String value1, String value2) {
            addCriterion("properties not between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andProductWeightIsNull() {
            addCriterion("product_weight is null");
            return (Criteria) this;
        }

        public Criteria andProductWeightIsNotNull() {
            addCriterion("product_weight is not null");
            return (Criteria) this;
        }

        public Criteria andProductWeightEqualTo(String value) {
            addCriterion("product_weight =", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotEqualTo(String value) {
            addCriterion("product_weight <>", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightGreaterThan(String value) {
            addCriterion("product_weight >", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightGreaterThanOrEqualTo(String value) {
            addCriterion("product_weight >=", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightLessThan(String value) {
            addCriterion("product_weight <", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightLessThanOrEqualTo(String value) {
            addCriterion("product_weight <=", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightLike(String value) {
            addCriterion("product_weight like", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotLike(String value) {
            addCriterion("product_weight not like", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightIn(List<String> values) {
            addCriterion("product_weight in", values, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotIn(List<String> values) {
            addCriterion("product_weight not in", values, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightBetween(String value1, String value2) {
            addCriterion("product_weight between", value1, value2, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotBetween(String value1, String value2) {
            addCriterion("product_weight not between", value1, value2, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductVolumeIsNull() {
            addCriterion("product_volume is null");
            return (Criteria) this;
        }

        public Criteria andProductVolumeIsNotNull() {
            addCriterion("product_volume is not null");
            return (Criteria) this;
        }

        public Criteria andProductVolumeEqualTo(String value) {
            addCriterion("product_volume =", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeNotEqualTo(String value) {
            addCriterion("product_volume <>", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeGreaterThan(String value) {
            addCriterion("product_volume >", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeGreaterThanOrEqualTo(String value) {
            addCriterion("product_volume >=", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeLessThan(String value) {
            addCriterion("product_volume <", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeLessThanOrEqualTo(String value) {
            addCriterion("product_volume <=", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeLike(String value) {
            addCriterion("product_volume like", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeNotLike(String value) {
            addCriterion("product_volume not like", value, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeIn(List<String> values) {
            addCriterion("product_volume in", values, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeNotIn(List<String> values) {
            addCriterion("product_volume not in", values, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeBetween(String value1, String value2) {
            addCriterion("product_volume between", value1, value2, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductVolumeNotBetween(String value1, String value2) {
            addCriterion("product_volume not between", value1, value2, "productVolume");
            return (Criteria) this;
        }

        public Criteria andProductLengthIsNull() {
            addCriterion("product_length is null");
            return (Criteria) this;
        }

        public Criteria andProductLengthIsNotNull() {
            addCriterion("product_length is not null");
            return (Criteria) this;
        }

        public Criteria andProductLengthEqualTo(String value) {
            addCriterion("product_length =", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotEqualTo(String value) {
            addCriterion("product_length <>", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthGreaterThan(String value) {
            addCriterion("product_length >", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthGreaterThanOrEqualTo(String value) {
            addCriterion("product_length >=", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthLessThan(String value) {
            addCriterion("product_length <", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthLessThanOrEqualTo(String value) {
            addCriterion("product_length <=", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthLike(String value) {
            addCriterion("product_length like", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotLike(String value) {
            addCriterion("product_length not like", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthIn(List<String> values) {
            addCriterion("product_length in", values, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotIn(List<String> values) {
            addCriterion("product_length not in", values, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthBetween(String value1, String value2) {
            addCriterion("product_length between", value1, value2, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotBetween(String value1, String value2) {
            addCriterion("product_length not between", value1, value2, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductWidthIsNull() {
            addCriterion("product_width is null");
            return (Criteria) this;
        }

        public Criteria andProductWidthIsNotNull() {
            addCriterion("product_width is not null");
            return (Criteria) this;
        }

        public Criteria andProductWidthEqualTo(String value) {
            addCriterion("product_width =", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthNotEqualTo(String value) {
            addCriterion("product_width <>", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthGreaterThan(String value) {
            addCriterion("product_width >", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthGreaterThanOrEqualTo(String value) {
            addCriterion("product_width >=", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthLessThan(String value) {
            addCriterion("product_width <", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthLessThanOrEqualTo(String value) {
            addCriterion("product_width <=", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthLike(String value) {
            addCriterion("product_width like", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthNotLike(String value) {
            addCriterion("product_width not like", value, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthIn(List<String> values) {
            addCriterion("product_width in", values, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthNotIn(List<String> values) {
            addCriterion("product_width not in", values, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthBetween(String value1, String value2) {
            addCriterion("product_width between", value1, value2, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductWidthNotBetween(String value1, String value2) {
            addCriterion("product_width not between", value1, value2, "productWidth");
            return (Criteria) this;
        }

        public Criteria andProductHighIsNull() {
            addCriterion("product_high is null");
            return (Criteria) this;
        }

        public Criteria andProductHighIsNotNull() {
            addCriterion("product_high is not null");
            return (Criteria) this;
        }

        public Criteria andProductHighEqualTo(String value) {
            addCriterion("product_high =", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighNotEqualTo(String value) {
            addCriterion("product_high <>", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighGreaterThan(String value) {
            addCriterion("product_high >", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighGreaterThanOrEqualTo(String value) {
            addCriterion("product_high >=", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighLessThan(String value) {
            addCriterion("product_high <", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighLessThanOrEqualTo(String value) {
            addCriterion("product_high <=", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighLike(String value) {
            addCriterion("product_high like", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighNotLike(String value) {
            addCriterion("product_high not like", value, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighIn(List<String> values) {
            addCriterion("product_high in", values, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighNotIn(List<String> values) {
            addCriterion("product_high not in", values, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighBetween(String value1, String value2) {
            addCriterion("product_high between", value1, value2, "productHigh");
            return (Criteria) this;
        }

        public Criteria andProductHighNotBetween(String value1, String value2) {
            addCriterion("product_high not between", value1, value2, "productHigh");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeIsNull() {
            addCriterion("sell_productcode is null");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeIsNotNull() {
            addCriterion("sell_productcode is not null");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeEqualTo(String value) {
            addCriterion("sell_productcode =", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeNotEqualTo(String value) {
            addCriterion("sell_productcode <>", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeGreaterThan(String value) {
            addCriterion("sell_productcode >", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeGreaterThanOrEqualTo(String value) {
            addCriterion("sell_productcode >=", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeLessThan(String value) {
            addCriterion("sell_productcode <", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeLessThanOrEqualTo(String value) {
            addCriterion("sell_productcode <=", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeLike(String value) {
            addCriterion("sell_productcode like", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeNotLike(String value) {
            addCriterion("sell_productcode not like", value, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeIn(List<String> values) {
            addCriterion("sell_productcode in", values, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeNotIn(List<String> values) {
            addCriterion("sell_productcode not in", values, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeBetween(String value1, String value2) {
            addCriterion("sell_productcode between", value1, value2, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andSellProductcodeNotBetween(String value1, String value2) {
            addCriterion("sell_productcode not between", value1, value2, "sellProductcode");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNull() {
            addCriterion("video_url is null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNotNull() {
            addCriterion("video_url is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlEqualTo(String value) {
            addCriterion("video_url =", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotEqualTo(String value) {
            addCriterion("video_url <>", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThan(String value) {
            addCriterion("video_url >", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("video_url >=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThan(String value) {
            addCriterion("video_url <", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("video_url <=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLike(String value) {
            addCriterion("video_url like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotLike(String value) {
            addCriterion("video_url not like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIn(List<String> values) {
            addCriterion("video_url in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotIn(List<String> values) {
            addCriterion("video_url not in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlBetween(String value1, String value2) {
            addCriterion("video_url between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotBetween(String value1, String value2) {
            addCriterion("video_url not between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidIsNull() {
            addCriterion("relevance_uid is null");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidIsNotNull() {
            addCriterion("relevance_uid is not null");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidEqualTo(String value) {
            addCriterion("relevance_uid =", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidNotEqualTo(String value) {
            addCriterion("relevance_uid <>", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidGreaterThan(String value) {
            addCriterion("relevance_uid >", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidGreaterThanOrEqualTo(String value) {
            addCriterion("relevance_uid >=", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidLessThan(String value) {
            addCriterion("relevance_uid <", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidLessThanOrEqualTo(String value) {
            addCriterion("relevance_uid <=", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidLike(String value) {
            addCriterion("relevance_uid like", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidNotLike(String value) {
            addCriterion("relevance_uid not like", value, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidIn(List<String> values) {
            addCriterion("relevance_uid in", values, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidNotIn(List<String> values) {
            addCriterion("relevance_uid not in", values, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidBetween(String value1, String value2) {
            addCriterion("relevance_uid between", value1, value2, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andRelevanceUidNotBetween(String value1, String value2) {
            addCriterion("relevance_uid not between", value1, value2, "relevanceUid");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNull() {
            addCriterion("fail_reason is null");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNotNull() {
            addCriterion("fail_reason is not null");
            return (Criteria) this;
        }

        public Criteria andFailReasonEqualTo(String value) {
            addCriterion("fail_reason =", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotEqualTo(String value) {
            addCriterion("fail_reason <>", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThan(String value) {
            addCriterion("fail_reason >", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThanOrEqualTo(String value) {
            addCriterion("fail_reason >=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThan(String value) {
            addCriterion("fail_reason <", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThanOrEqualTo(String value) {
            addCriterion("fail_reason <=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLike(String value) {
            addCriterion("fail_reason like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotLike(String value) {
            addCriterion("fail_reason not like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonIn(List<String> values) {
            addCriterion("fail_reason in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotIn(List<String> values) {
            addCriterion("fail_reason not in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonBetween(String value1, String value2) {
            addCriterion("fail_reason between", value1, value2, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotBetween(String value1, String value2) {
            addCriterion("fail_reason not between", value1, value2, "failReason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lc_productinfo_batch
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}