package com.cmall.dborm.txmodel;

public class NcPostOperate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.operater_code
     *
     * @mbggenerated
     */
    private String operaterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.info_code
     *
     * @mbggenerated
     */
    private String infoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.share_type
     *
     * @mbggenerated
     */
    private String shareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.operate_type
     *
     * @mbggenerated
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.app_code
     *
     * @mbggenerated
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.post_parent_code
     *
     * @mbggenerated
     */
    private String postParentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_post_operate.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.zid
     *
     * @return the value of nc_post_operate.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.zid
     *
     * @param zid the value for nc_post_operate.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.uid
     *
     * @return the value of nc_post_operate.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.uid
     *
     * @param uid the value for nc_post_operate.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.operater_code
     *
     * @return the value of nc_post_operate.operater_code
     *
     * @mbggenerated
     */
    public String getOperaterCode() {
        return operaterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.operater_code
     *
     * @param operaterCode the value for nc_post_operate.operater_code
     *
     * @mbggenerated
     */
    public void setOperaterCode(String operaterCode) {
        this.operaterCode = operaterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.info_code
     *
     * @return the value of nc_post_operate.info_code
     *
     * @mbggenerated
     */
    public String getInfoCode() {
        return infoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.info_code
     *
     * @param infoCode the value for nc_post_operate.info_code
     *
     * @mbggenerated
     */
    public void setInfoCode(String infoCode) {
        this.infoCode = infoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.share_type
     *
     * @return the value of nc_post_operate.share_type
     *
     * @mbggenerated
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.share_type
     *
     * @param shareType the value for nc_post_operate.share_type
     *
     * @mbggenerated
     */
    public void setShareType(String shareType) {
        this.shareType = shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.operate_type
     *
     * @return the value of nc_post_operate.operate_type
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.operate_type
     *
     * @param operateType the value for nc_post_operate.operate_type
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.flag
     *
     * @return the value of nc_post_operate.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.flag
     *
     * @param flag the value for nc_post_operate.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.app_code
     *
     * @return the value of nc_post_operate.app_code
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.app_code
     *
     * @param appCode the value for nc_post_operate.app_code
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.post_parent_code
     *
     * @return the value of nc_post_operate.post_parent_code
     *
     * @mbggenerated
     */
    public String getPostParentCode() {
        return postParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.post_parent_code
     *
     * @param postParentCode the value for nc_post_operate.post_parent_code
     *
     * @mbggenerated
     */
    public void setPostParentCode(String postParentCode) {
        this.postParentCode = postParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_post_operate.end_time
     *
     * @return the value of nc_post_operate.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_post_operate.end_time
     *
     * @param endTime the value for nc_post_operate.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}