package com.cmall.dborm.txmodel;

public class OcOrderPayWithBLOBs extends OcOrderPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_order_pay.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_order_pay.param_value
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_order_pay.sign
     *
     * @return the value of oc_order_pay.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_order_pay.sign
     *
     * @param sign the value for oc_order_pay.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_order_pay.param_value
     *
     * @return the value of oc_order_pay.param_value
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_order_pay.param_value
     *
     * @param paramValue the value for oc_order_pay.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}