package com.cmall.dborm.txmodel;

public class OcTryoutProducts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.activity_code
     *
     * @mbggenerated
     */
    private String activityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.sku_code
     *
     * @mbggenerated
     */
    private String skuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.app_code
     *
     * @mbggenerated
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.tryout_price
     *
     * @mbggenerated
     */
    private String tryoutPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.level_code
     *
     * @mbggenerated
     */
    private String levelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.tryout_inventory
     *
     * @mbggenerated
     */
    private Integer tryoutInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.init_inventory
     *
     * @mbggenerated
     */
    private Integer initInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_tryout_products.sku_name
     *
     * @mbggenerated
     */
    private String skuName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.zid
     *
     * @return the value of oc_tryout_products.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.zid
     *
     * @param zid the value for oc_tryout_products.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.uid
     *
     * @return the value of oc_tryout_products.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.uid
     *
     * @param uid the value for oc_tryout_products.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.activity_code
     *
     * @return the value of oc_tryout_products.activity_code
     *
     * @mbggenerated
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.activity_code
     *
     * @param activityCode the value for oc_tryout_products.activity_code
     *
     * @mbggenerated
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.sku_code
     *
     * @return the value of oc_tryout_products.sku_code
     *
     * @mbggenerated
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.sku_code
     *
     * @param skuCode the value for oc_tryout_products.sku_code
     *
     * @mbggenerated
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.app_code
     *
     * @return the value of oc_tryout_products.app_code
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.app_code
     *
     * @param appCode the value for oc_tryout_products.app_code
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.tryout_price
     *
     * @return the value of oc_tryout_products.tryout_price
     *
     * @mbggenerated
     */
    public String getTryoutPrice() {
        return tryoutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.tryout_price
     *
     * @param tryoutPrice the value for oc_tryout_products.tryout_price
     *
     * @mbggenerated
     */
    public void setTryoutPrice(String tryoutPrice) {
        this.tryoutPrice = tryoutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.level_code
     *
     * @return the value of oc_tryout_products.level_code
     *
     * @mbggenerated
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.level_code
     *
     * @param levelCode the value for oc_tryout_products.level_code
     *
     * @mbggenerated
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.tryout_inventory
     *
     * @return the value of oc_tryout_products.tryout_inventory
     *
     * @mbggenerated
     */
    public Integer getTryoutInventory() {
        return tryoutInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.tryout_inventory
     *
     * @param tryoutInventory the value for oc_tryout_products.tryout_inventory
     *
     * @mbggenerated
     */
    public void setTryoutInventory(Integer tryoutInventory) {
        this.tryoutInventory = tryoutInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.init_inventory
     *
     * @return the value of oc_tryout_products.init_inventory
     *
     * @mbggenerated
     */
    public Integer getInitInventory() {
        return initInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.init_inventory
     *
     * @param initInventory the value for oc_tryout_products.init_inventory
     *
     * @mbggenerated
     */
    public void setInitInventory(Integer initInventory) {
        this.initInventory = initInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.start_time
     *
     * @return the value of oc_tryout_products.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.start_time
     *
     * @param startTime the value for oc_tryout_products.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.end_time
     *
     * @return the value of oc_tryout_products.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.end_time
     *
     * @param endTime the value for oc_tryout_products.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.create_user
     *
     * @return the value of oc_tryout_products.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.create_user
     *
     * @param createUser the value for oc_tryout_products.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.create_time
     *
     * @return the value of oc_tryout_products.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.create_time
     *
     * @param createTime the value for oc_tryout_products.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.update_user
     *
     * @return the value of oc_tryout_products.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.update_user
     *
     * @param updateUser the value for oc_tryout_products.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.update_time
     *
     * @return the value of oc_tryout_products.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.update_time
     *
     * @param updateTime the value for oc_tryout_products.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_tryout_products.sku_name
     *
     * @return the value of oc_tryout_products.sku_name
     *
     * @mbggenerated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_tryout_products.sku_name
     *
     * @param skuName the value for oc_tryout_products.sku_name
     *
     * @mbggenerated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }
}