package com.cmall.dborm.txmodel;

public class PcStockDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.sku_code
     *
     * @mbggenerated
     */
    private String skuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.stock_number
     *
     * @mbggenerated
     */
    private Integer stockNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.stock_batch
     *
     * @mbggenerated
     */
    private String stockBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.quality_time
     *
     * @mbggenerated
     */
    private String qualityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_stock_detail.stock_area
     *
     * @mbggenerated
     */
    private String stockArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.zid
     *
     * @return the value of pc_stock_detail.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.zid
     *
     * @param zid the value for pc_stock_detail.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.uid
     *
     * @return the value of pc_stock_detail.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.uid
     *
     * @param uid the value for pc_stock_detail.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.sku_code
     *
     * @return the value of pc_stock_detail.sku_code
     *
     * @mbggenerated
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.sku_code
     *
     * @param skuCode the value for pc_stock_detail.sku_code
     *
     * @mbggenerated
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.stock_number
     *
     * @return the value of pc_stock_detail.stock_number
     *
     * @mbggenerated
     */
    public Integer getStockNumber() {
        return stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.stock_number
     *
     * @param stockNumber the value for pc_stock_detail.stock_number
     *
     * @mbggenerated
     */
    public void setStockNumber(Integer stockNumber) {
        this.stockNumber = stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.stock_batch
     *
     * @return the value of pc_stock_detail.stock_batch
     *
     * @mbggenerated
     */
    public String getStockBatch() {
        return stockBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.stock_batch
     *
     * @param stockBatch the value for pc_stock_detail.stock_batch
     *
     * @mbggenerated
     */
    public void setStockBatch(String stockBatch) {
        this.stockBatch = stockBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.quality_time
     *
     * @return the value of pc_stock_detail.quality_time
     *
     * @mbggenerated
     */
    public String getQualityTime() {
        return qualityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.quality_time
     *
     * @param qualityTime the value for pc_stock_detail.quality_time
     *
     * @mbggenerated
     */
    public void setQualityTime(String qualityTime) {
        this.qualityTime = qualityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_stock_detail.stock_area
     *
     * @return the value of pc_stock_detail.stock_area
     *
     * @mbggenerated
     */
    public String getStockArea() {
        return stockArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_stock_detail.stock_area
     *
     * @param stockArea the value for pc_stock_detail.stock_area
     *
     * @mbggenerated
     */
    public void setStockArea(String stockArea) {
        this.stockArea = stockArea;
    }
}