package com.cmall.dborm.txmodel;

public class TestCall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.dropdown
     *
     * @mbggenerated
     */
    private String dropdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.listbox
     *
     * @mbggenerated
     */
    private String listbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.t1
     *
     * @mbggenerated
     */
    private String t1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.t2
     *
     * @mbggenerated
     */
    private String t2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.t3
     *
     * @mbggenerated
     */
    private String t3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_call.editor2
     *
     * @mbggenerated
     */
    private String editor2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.zid
     *
     * @return the value of test_call.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.zid
     *
     * @param zid the value for test_call.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.uid
     *
     * @return the value of test_call.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.uid
     *
     * @param uid the value for test_call.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.dropdown
     *
     * @return the value of test_call.dropdown
     *
     * @mbggenerated
     */
    public String getDropdown() {
        return dropdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.dropdown
     *
     * @param dropdown the value for test_call.dropdown
     *
     * @mbggenerated
     */
    public void setDropdown(String dropdown) {
        this.dropdown = dropdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.editor
     *
     * @return the value of test_call.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.editor
     *
     * @param editor the value for test_call.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.listbox
     *
     * @return the value of test_call.listbox
     *
     * @mbggenerated
     */
    public String getListbox() {
        return listbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.listbox
     *
     * @param listbox the value for test_call.listbox
     *
     * @mbggenerated
     */
    public void setListbox(String listbox) {
        this.listbox = listbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.t1
     *
     * @return the value of test_call.t1
     *
     * @mbggenerated
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.t1
     *
     * @param t1 the value for test_call.t1
     *
     * @mbggenerated
     */
    public void setT1(String t1) {
        this.t1 = t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.t2
     *
     * @return the value of test_call.t2
     *
     * @mbggenerated
     */
    public String getT2() {
        return t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.t2
     *
     * @param t2 the value for test_call.t2
     *
     * @mbggenerated
     */
    public void setT2(String t2) {
        this.t2 = t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.t3
     *
     * @return the value of test_call.t3
     *
     * @mbggenerated
     */
    public String getT3() {
        return t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.t3
     *
     * @param t3 the value for test_call.t3
     *
     * @mbggenerated
     */
    public void setT3(String t3) {
        this.t3 = t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_call.editor2
     *
     * @return the value of test_call.editor2
     *
     * @mbggenerated
     */
    public String getEditor2() {
        return editor2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_call.editor2
     *
     * @param editor2 the value for test_call.editor2
     *
     * @mbggenerated
     */
    public void setEditor2(String editor2) {
        this.editor2 = editor2;
    }
}