package com.cmall.dborm.txmodel;

public class ZwError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.error_code
     *
     * @mbggenerated
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.error_type
     *
     * @mbggenerated
     */
    private String errorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.error_level
     *
     * @mbggenerated
     */
    private String errorLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.error_source
     *
     * @mbggenerated
     */
    private String errorSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zw_error.error_info
     *
     * @mbggenerated
     */
    private String errorInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.zid
     *
     * @return the value of zw_error.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.zid
     *
     * @param zid the value for zw_error.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.uid
     *
     * @return the value of zw_error.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.uid
     *
     * @param uid the value for zw_error.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.error_code
     *
     * @return the value of zw_error.error_code
     *
     * @mbggenerated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.error_code
     *
     * @param errorCode the value for zw_error.error_code
     *
     * @mbggenerated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.error_type
     *
     * @return the value of zw_error.error_type
     *
     * @mbggenerated
     */
    public String getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.error_type
     *
     * @param errorType the value for zw_error.error_type
     *
     * @mbggenerated
     */
    public void setErrorType(String errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.error_level
     *
     * @return the value of zw_error.error_level
     *
     * @mbggenerated
     */
    public String getErrorLevel() {
        return errorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.error_level
     *
     * @param errorLevel the value for zw_error.error_level
     *
     * @mbggenerated
     */
    public void setErrorLevel(String errorLevel) {
        this.errorLevel = errorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.error_source
     *
     * @return the value of zw_error.error_source
     *
     * @mbggenerated
     */
    public String getErrorSource() {
        return errorSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.error_source
     *
     * @param errorSource the value for zw_error.error_source
     *
     * @mbggenerated
     */
    public void setErrorSource(String errorSource) {
        this.errorSource = errorSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.create_time
     *
     * @return the value of zw_error.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.create_time
     *
     * @param createTime the value for zw_error.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zw_error.error_info
     *
     * @return the value of zw_error.error_info
     *
     * @mbggenerated
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zw_error.error_info
     *
     * @param errorInfo the value for zw_error.error_info
     *
     * @mbggenerated
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo;
    }
}