package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.JifenLog;
import com.cmall.dborm.txmodel.JifenLogExample;
import com.cmall.dborm.txmodel.JifenLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JifenLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int countByExample(JifenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int deleteByExample(JifenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(JifenLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int insert(JifenLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int insertSelective(JifenLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    List<JifenLog> selectByExample(JifenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    JifenLog selectByPrimaryKey(JifenLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JifenLog record, @Param("example") JifenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JifenLog record, @Param("example") JifenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JifenLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JifenLog record);
}