package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.OcReturnGoods;
import com.cmall.dborm.txmodel.OcReturnGoodsExample;
import com.cmall.dborm.txmodel.OcReturnGoodsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OcReturnGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int countByExample(OcReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int deleteByExample(OcReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OcReturnGoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int insert(OcReturnGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int insertSelective(OcReturnGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    List<OcReturnGoods> selectByExample(OcReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    OcReturnGoods selectByPrimaryKey(OcReturnGoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OcReturnGoods record, @Param("example") OcReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OcReturnGoods record, @Param("example") OcReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OcReturnGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_return_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcReturnGoods record);
}