package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.PcProductpic;
import com.cmall.dborm.txmodel.PcProductpicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcProductpicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int countByExample(PcProductpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int deleteByExample(PcProductpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int insert(PcProductpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int insertSelective(PcProductpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    List<PcProductpic> selectByExample(PcProductpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    PcProductpic selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PcProductpic record, @Param("example") PcProductpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PcProductpic record, @Param("example") PcProductpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PcProductpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productpic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PcProductpic record);
}