package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.PcProductdescription;
import com.cmall.dborm.txmodel.PcProductdescriptionExample;
import com.cmall.dborm.txmodel.PcProductdescriptionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcProductdescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int countByExample(PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int deleteByExample(PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int insert(PcProductdescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int insertSelective(PcProductdescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    List<PcProductdescriptionWithBLOBs> selectByExampleWithBLOBs(PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    List<PcProductdescription> selectByExample(PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    PcProductdescriptionWithBLOBs selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PcProductdescriptionWithBLOBs record, @Param("example") PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") PcProductdescriptionWithBLOBs record, @Param("example") PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PcProductdescription record, @Param("example") PcProductdescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PcProductdescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PcProductdescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productdescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PcProductdescription record);
}