package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.PcSellerQualification;
import com.cmall.dborm.txmodel.PcSellerQualificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcSellerQualificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int countByExample(PcSellerQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int deleteByExample(PcSellerQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int insert(PcSellerQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int insertSelective(PcSellerQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    List<PcSellerQualification> selectByExample(PcSellerQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    PcSellerQualification selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PcSellerQualification record, @Param("example") PcSellerQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PcSellerQualification record, @Param("example") PcSellerQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PcSellerQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_seller_qualification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PcSellerQualification record);
}