package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.PcSkuinfo;
import com.cmall.dborm.txmodel.PcSkuinfoExample;
import com.cmall.dborm.txmodel.PcSkuinfoWithBLOBs;
import com.cmall.dborm.txmodel.PcSkuinfoWithBLOBsForD;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcSkuinfoMapperForD {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int countByExample(PcSkuinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int deleteByExample(PcSkuinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer zid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int insert(PcSkuinfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int insertSelective(PcSkuinfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	List<PcSkuinfoWithBLOBs> selectByExampleWithBLOBs(PcSkuinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	List<PcSkuinfo> selectByExample(PcSkuinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	PcSkuinfoWithBLOBs selectByPrimaryKey(Integer zid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PcSkuinfoWithBLOBs record,
			@Param("example") PcSkuinfoExample example);
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByExampleSelectiveForSkuName(@Param("record") PcSkuinfoWithBLOBsForD record,
			@Param("example") PcSkuinfoExample example);
	
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") PcSkuinfoWithBLOBs record,
			@Param("example") PcSkuinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PcSkuinfo record,
			@Param("example") PcSkuinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PcSkuinfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(PcSkuinfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pc_skuinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PcSkuinfo record);
}