package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.ScFullCut;
import com.cmall.dborm.txmodel.ScFullCutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScFullCutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int countByExample(ScFullCutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int deleteByExample(ScFullCutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int insert(ScFullCut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int insertSelective(ScFullCut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    List<ScFullCut> selectByExample(ScFullCutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    ScFullCut selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ScFullCut record, @Param("example") ScFullCutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ScFullCut record, @Param("example") ScFullCutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScFullCut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_full_cut
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScFullCut record);
}