package com.cmall.dborm.txmapper;

import com.cmall.dborm.txmodel.UcSellercategoryProductRelation;
import com.cmall.dborm.txmodel.UcSellercategoryProductRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcSellercategoryProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int countByExample(UcSellercategoryProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int deleteByExample(UcSellercategoryProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int insert(UcSellercategoryProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int insertSelective(UcSellercategoryProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    List<UcSellercategoryProductRelation> selectByExample(UcSellercategoryProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    UcSellercategoryProductRelation selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UcSellercategoryProductRelation record, @Param("example") UcSellercategoryProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UcSellercategoryProductRelation record, @Param("example") UcSellercategoryProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UcSellercategoryProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_sellercategory_product_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UcSellercategoryProductRelation record);
}