package com.cmall.dborm.txmodel.groupcenter;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class GcGroupLevelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public GcGroupLevelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZidIsNull() {
            addCriterion("zid is null");
            return (Criteria) this;
        }

        public Criteria andZidIsNotNull() {
            addCriterion("zid is not null");
            return (Criteria) this;
        }

        public Criteria andZidEqualTo(Integer value) {
            addCriterion("zid =", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotEqualTo(Integer value) {
            addCriterion("zid <>", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThan(Integer value) {
            addCriterion("zid >", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThanOrEqualTo(Integer value) {
            addCriterion("zid >=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThan(Integer value) {
            addCriterion("zid <", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThanOrEqualTo(Integer value) {
            addCriterion("zid <=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidIn(List<Integer> values) {
            addCriterion("zid in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotIn(List<Integer> values) {
            addCriterion("zid not in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidBetween(Integer value1, Integer value2) {
            addCriterion("zid between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotBetween(Integer value1, Integer value2) {
            addCriterion("zid not between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andLevelCodeIsNull() {
            addCriterion("level_code is null");
            return (Criteria) this;
        }

        public Criteria andLevelCodeIsNotNull() {
            addCriterion("level_code is not null");
            return (Criteria) this;
        }

        public Criteria andLevelCodeEqualTo(String value) {
            addCriterion("level_code =", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeNotEqualTo(String value) {
            addCriterion("level_code <>", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeGreaterThan(String value) {
            addCriterion("level_code >", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("level_code >=", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeLessThan(String value) {
            addCriterion("level_code <", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeLessThanOrEqualTo(String value) {
            addCriterion("level_code <=", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeLike(String value) {
            addCriterion("level_code like", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeNotLike(String value) {
            addCriterion("level_code not like", value, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeIn(List<String> values) {
            addCriterion("level_code in", values, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeNotIn(List<String> values) {
            addCriterion("level_code not in", values, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeBetween(String value1, String value2) {
            addCriterion("level_code between", value1, value2, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelCodeNotBetween(String value1, String value2) {
            addCriterion("level_code not between", value1, value2, "levelCode");
            return (Criteria) this;
        }

        public Criteria andLevelNameIsNull() {
            addCriterion("level_name is null");
            return (Criteria) this;
        }

        public Criteria andLevelNameIsNotNull() {
            addCriterion("level_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevelNameEqualTo(String value) {
            addCriterion("level_name =", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotEqualTo(String value) {
            addCriterion("level_name <>", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameGreaterThan(String value) {
            addCriterion("level_name >", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameGreaterThanOrEqualTo(String value) {
            addCriterion("level_name >=", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLessThan(String value) {
            addCriterion("level_name <", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLessThanOrEqualTo(String value) {
            addCriterion("level_name <=", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLike(String value) {
            addCriterion("level_name like", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotLike(String value) {
            addCriterion("level_name not like", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameIn(List<String> values) {
            addCriterion("level_name in", values, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotIn(List<String> values) {
            addCriterion("level_name not in", values, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameBetween(String value1, String value2) {
            addCriterion("level_name between", value1, value2, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotBetween(String value1, String value2) {
            addCriterion("level_name not between", value1, value2, "levelName");
            return (Criteria) this;
        }

        public Criteria andManageCodeIsNull() {
            addCriterion("manage_code is null");
            return (Criteria) this;
        }

        public Criteria andManageCodeIsNotNull() {
            addCriterion("manage_code is not null");
            return (Criteria) this;
        }

        public Criteria andManageCodeEqualTo(String value) {
            addCriterion("manage_code =", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeNotEqualTo(String value) {
            addCriterion("manage_code <>", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeGreaterThan(String value) {
            addCriterion("manage_code >", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeGreaterThanOrEqualTo(String value) {
            addCriterion("manage_code >=", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeLessThan(String value) {
            addCriterion("manage_code <", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeLessThanOrEqualTo(String value) {
            addCriterion("manage_code <=", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeLike(String value) {
            addCriterion("manage_code like", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeNotLike(String value) {
            addCriterion("manage_code not like", value, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeIn(List<String> values) {
            addCriterion("manage_code in", values, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeNotIn(List<String> values) {
            addCriterion("manage_code not in", values, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeBetween(String value1, String value2) {
            addCriterion("manage_code between", value1, value2, "manageCode");
            return (Criteria) this;
        }

        public Criteria andManageCodeNotBetween(String value1, String value2) {
            addCriterion("manage_code not between", value1, value2, "manageCode");
            return (Criteria) this;
        }

        public Criteria andScaleReckonIsNull() {
            addCriterion("scale_reckon is null");
            return (Criteria) this;
        }

        public Criteria andScaleReckonIsNotNull() {
            addCriterion("scale_reckon is not null");
            return (Criteria) this;
        }

        public Criteria andScaleReckonEqualTo(BigDecimal value) {
            addCriterion("scale_reckon =", value, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonNotEqualTo(BigDecimal value) {
            addCriterion("scale_reckon <>", value, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonGreaterThan(BigDecimal value) {
            addCriterion("scale_reckon >", value, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("scale_reckon >=", value, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonLessThan(BigDecimal value) {
            addCriterion("scale_reckon <", value, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonLessThanOrEqualTo(BigDecimal value) {
            addCriterion("scale_reckon <=", value, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonIn(List<BigDecimal> values) {
            addCriterion("scale_reckon in", values, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonNotIn(List<BigDecimal> values) {
            addCriterion("scale_reckon not in", values, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("scale_reckon between", value1, value2, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andScaleReckonNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("scale_reckon not between", value1, value2, "scaleReckon");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersIsNull() {
            addCriterion("upgrade_members is null");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersIsNotNull() {
            addCriterion("upgrade_members is not null");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersEqualTo(Integer value) {
            addCriterion("upgrade_members =", value, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersNotEqualTo(Integer value) {
            addCriterion("upgrade_members <>", value, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersGreaterThan(Integer value) {
            addCriterion("upgrade_members >", value, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersGreaterThanOrEqualTo(Integer value) {
            addCriterion("upgrade_members >=", value, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersLessThan(Integer value) {
            addCriterion("upgrade_members <", value, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersLessThanOrEqualTo(Integer value) {
            addCriterion("upgrade_members <=", value, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersIn(List<Integer> values) {
            addCriterion("upgrade_members in", values, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersNotIn(List<Integer> values) {
            addCriterion("upgrade_members not in", values, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersBetween(Integer value1, Integer value2) {
            addCriterion("upgrade_members between", value1, value2, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeMembersNotBetween(Integer value1, Integer value2) {
            addCriterion("upgrade_members not between", value1, value2, "upgradeMembers");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeIsNull() {
            addCriterion("upgrade_consume is null");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeIsNotNull() {
            addCriterion("upgrade_consume is not null");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeEqualTo(BigDecimal value) {
            addCriterion("upgrade_consume =", value, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeNotEqualTo(BigDecimal value) {
            addCriterion("upgrade_consume <>", value, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeGreaterThan(BigDecimal value) {
            addCriterion("upgrade_consume >", value, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("upgrade_consume >=", value, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeLessThan(BigDecimal value) {
            addCriterion("upgrade_consume <", value, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("upgrade_consume <=", value, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeIn(List<BigDecimal> values) {
            addCriterion("upgrade_consume in", values, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeNotIn(List<BigDecimal> values) {
            addCriterion("upgrade_consume not in", values, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("upgrade_consume between", value1, value2, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andUpgradeConsumeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("upgrade_consume not between", value1, value2, "upgradeConsume");
            return (Criteria) this;
        }

        public Criteria andLevelSortIsNull() {
            addCriterion("level_sort is null");
            return (Criteria) this;
        }

        public Criteria andLevelSortIsNotNull() {
            addCriterion("level_sort is not null");
            return (Criteria) this;
        }

        public Criteria andLevelSortEqualTo(Integer value) {
            addCriterion("level_sort =", value, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortNotEqualTo(Integer value) {
            addCriterion("level_sort <>", value, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortGreaterThan(Integer value) {
            addCriterion("level_sort >", value, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_sort >=", value, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortLessThan(Integer value) {
            addCriterion("level_sort <", value, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortLessThanOrEqualTo(Integer value) {
            addCriterion("level_sort <=", value, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortIn(List<Integer> values) {
            addCriterion("level_sort in", values, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortNotIn(List<Integer> values) {
            addCriterion("level_sort not in", values, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortBetween(Integer value1, Integer value2) {
            addCriterion("level_sort between", value1, value2, "levelSort");
            return (Criteria) this;
        }

        public Criteria andLevelSortNotBetween(Integer value1, Integer value2) {
            addCriterion("level_sort not between", value1, value2, "levelSort");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNull() {
            addCriterion("flag_enable is null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNotNull() {
            addCriterion("flag_enable is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableEqualTo(Integer value) {
            addCriterion("flag_enable =", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotEqualTo(Integer value) {
            addCriterion("flag_enable <>", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThan(Integer value) {
            addCriterion("flag_enable >", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag_enable >=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThan(Integer value) {
            addCriterion("flag_enable <", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThanOrEqualTo(Integer value) {
            addCriterion("flag_enable <=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIn(List<Integer> values) {
            addCriterion("flag_enable in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotIn(List<Integer> values) {
            addCriterion("flag_enable not in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableBetween(Integer value1, Integer value2) {
            addCriterion("flag_enable between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("flag_enable not between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andLevelTypeIsNull() {
            addCriterion("level_type is null");
            return (Criteria) this;
        }

        public Criteria andLevelTypeIsNotNull() {
            addCriterion("level_type is not null");
            return (Criteria) this;
        }

        public Criteria andLevelTypeEqualTo(String value) {
            addCriterion("level_type =", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeNotEqualTo(String value) {
            addCriterion("level_type <>", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeGreaterThan(String value) {
            addCriterion("level_type >", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("level_type >=", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeLessThan(String value) {
            addCriterion("level_type <", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeLessThanOrEqualTo(String value) {
            addCriterion("level_type <=", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeLike(String value) {
            addCriterion("level_type like", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeNotLike(String value) {
            addCriterion("level_type not like", value, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeIn(List<String> values) {
            addCriterion("level_type in", values, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeNotIn(List<String> values) {
            addCriterion("level_type not in", values, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeBetween(String value1, String value2) {
            addCriterion("level_type between", value1, value2, "levelType");
            return (Criteria) this;
        }

        public Criteria andLevelTypeNotBetween(String value1, String value2) {
            addCriterion("level_type not between", value1, value2, "levelType");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeIsNull() {
            addCriterion("deep_consume is null");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeIsNotNull() {
            addCriterion("deep_consume is not null");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeEqualTo(Integer value) {
            addCriterion("deep_consume =", value, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeNotEqualTo(Integer value) {
            addCriterion("deep_consume <>", value, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeGreaterThan(Integer value) {
            addCriterion("deep_consume >", value, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deep_consume >=", value, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeLessThan(Integer value) {
            addCriterion("deep_consume <", value, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeLessThanOrEqualTo(Integer value) {
            addCriterion("deep_consume <=", value, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeIn(List<Integer> values) {
            addCriterion("deep_consume in", values, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeNotIn(List<Integer> values) {
            addCriterion("deep_consume not in", values, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeBetween(Integer value1, Integer value2) {
            addCriterion("deep_consume between", value1, value2, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepConsumeNotBetween(Integer value1, Integer value2) {
            addCriterion("deep_consume not between", value1, value2, "deepConsume");
            return (Criteria) this;
        }

        public Criteria andDeepReckonIsNull() {
            addCriterion("deep_reckon is null");
            return (Criteria) this;
        }

        public Criteria andDeepReckonIsNotNull() {
            addCriterion("deep_reckon is not null");
            return (Criteria) this;
        }

        public Criteria andDeepReckonEqualTo(Integer value) {
            addCriterion("deep_reckon =", value, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonNotEqualTo(Integer value) {
            addCriterion("deep_reckon <>", value, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonGreaterThan(Integer value) {
            addCriterion("deep_reckon >", value, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonGreaterThanOrEqualTo(Integer value) {
            addCriterion("deep_reckon >=", value, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonLessThan(Integer value) {
            addCriterion("deep_reckon <", value, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonLessThanOrEqualTo(Integer value) {
            addCriterion("deep_reckon <=", value, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonIn(List<Integer> values) {
            addCriterion("deep_reckon in", values, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonNotIn(List<Integer> values) {
            addCriterion("deep_reckon not in", values, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonBetween(Integer value1, Integer value2) {
            addCriterion("deep_reckon between", value1, value2, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andDeepReckonNotBetween(Integer value1, Integer value2) {
            addCriterion("deep_reckon not between", value1, value2, "deepReckon");
            return (Criteria) this;
        }

        public Criteria andNextLevelIsNull() {
            addCriterion("next_level is null");
            return (Criteria) this;
        }

        public Criteria andNextLevelIsNotNull() {
            addCriterion("next_level is not null");
            return (Criteria) this;
        }

        public Criteria andNextLevelEqualTo(String value) {
            addCriterion("next_level =", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelNotEqualTo(String value) {
            addCriterion("next_level <>", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelGreaterThan(String value) {
            addCriterion("next_level >", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelGreaterThanOrEqualTo(String value) {
            addCriterion("next_level >=", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelLessThan(String value) {
            addCriterion("next_level <", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelLessThanOrEqualTo(String value) {
            addCriterion("next_level <=", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelLike(String value) {
            addCriterion("next_level like", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelNotLike(String value) {
            addCriterion("next_level not like", value, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelIn(List<String> values) {
            addCriterion("next_level in", values, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelNotIn(List<String> values) {
            addCriterion("next_level not in", values, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelBetween(String value1, String value2) {
            addCriterion("next_level between", value1, value2, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andNextLevelNotBetween(String value1, String value2) {
            addCriterion("next_level not between", value1, value2, "nextLevel");
            return (Criteria) this;
        }

        public Criteria andFlagFallIsNull() {
            addCriterion("flag_fall is null");
            return (Criteria) this;
        }

        public Criteria andFlagFallIsNotNull() {
            addCriterion("flag_fall is not null");
            return (Criteria) this;
        }

        public Criteria andFlagFallEqualTo(Integer value) {
            addCriterion("flag_fall =", value, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallNotEqualTo(Integer value) {
            addCriterion("flag_fall <>", value, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallGreaterThan(Integer value) {
            addCriterion("flag_fall >", value, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag_fall >=", value, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallLessThan(Integer value) {
            addCriterion("flag_fall <", value, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallLessThanOrEqualTo(Integer value) {
            addCriterion("flag_fall <=", value, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallIn(List<Integer> values) {
            addCriterion("flag_fall in", values, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallNotIn(List<Integer> values) {
            addCriterion("flag_fall not in", values, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallBetween(Integer value1, Integer value2) {
            addCriterion("flag_fall between", value1, value2, "flagFall");
            return (Criteria) this;
        }

        public Criteria andFlagFallNotBetween(Integer value1, Integer value2) {
            addCriterion("flag_fall not between", value1, value2, "flagFall");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gc_group_level
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gc_group_level
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}