package com.cmall.dborm.txmodel.groupcenter;

public class GcMemberBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.bank_code
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.member_code
     *
     * @mbggenerated
     */
    private String memberCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.account_code
     *
     * @mbggenerated
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.card_code
     *
     * @mbggenerated
     */
    private String cardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.papers_type
     *
     * @mbggenerated
     */
    private String papersType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.papers_code
     *
     * @mbggenerated
     */
    private String papersCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.bank_phone
     *
     * @mbggenerated
     */
    private String bankPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.bank_verify
     *
     * @mbggenerated
     */
    private String bankVerify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.delete_time
     *
     * @mbggenerated
     */
    private String deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.sort_num
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.card_kind
     *
     * @mbggenerated
     */
    private String cardKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gc_member_bank.bank_icon_uid
     *
     * @mbggenerated
     */
    private String bankIconUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.zid
     *
     * @return the value of gc_member_bank.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.zid
     *
     * @param zid the value for gc_member_bank.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.uid
     *
     * @return the value of gc_member_bank.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.uid
     *
     * @param uid the value for gc_member_bank.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.bank_code
     *
     * @return the value of gc_member_bank.bank_code
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.bank_code
     *
     * @param bankCode the value for gc_member_bank.bank_code
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.member_code
     *
     * @return the value of gc_member_bank.member_code
     *
     * @mbggenerated
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.member_code
     *
     * @param memberCode the value for gc_member_bank.member_code
     *
     * @mbggenerated
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.account_code
     *
     * @return the value of gc_member_bank.account_code
     *
     * @mbggenerated
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.account_code
     *
     * @param accountCode the value for gc_member_bank.account_code
     *
     * @mbggenerated
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.bank_name
     *
     * @return the value of gc_member_bank.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.bank_name
     *
     * @param bankName the value for gc_member_bank.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.card_code
     *
     * @return the value of gc_member_bank.card_code
     *
     * @mbggenerated
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.card_code
     *
     * @param cardCode the value for gc_member_bank.card_code
     *
     * @mbggenerated
     */
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.user_name
     *
     * @return the value of gc_member_bank.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.user_name
     *
     * @param userName the value for gc_member_bank.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.papers_type
     *
     * @return the value of gc_member_bank.papers_type
     *
     * @mbggenerated
     */
    public String getPapersType() {
        return papersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.papers_type
     *
     * @param papersType the value for gc_member_bank.papers_type
     *
     * @mbggenerated
     */
    public void setPapersType(String papersType) {
        this.papersType = papersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.papers_code
     *
     * @return the value of gc_member_bank.papers_code
     *
     * @mbggenerated
     */
    public String getPapersCode() {
        return papersCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.papers_code
     *
     * @param papersCode the value for gc_member_bank.papers_code
     *
     * @mbggenerated
     */
    public void setPapersCode(String papersCode) {
        this.papersCode = papersCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.bank_phone
     *
     * @return the value of gc_member_bank.bank_phone
     *
     * @mbggenerated
     */
    public String getBankPhone() {
        return bankPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.bank_phone
     *
     * @param bankPhone the value for gc_member_bank.bank_phone
     *
     * @mbggenerated
     */
    public void setBankPhone(String bankPhone) {
        this.bankPhone = bankPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.create_time
     *
     * @return the value of gc_member_bank.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.create_time
     *
     * @param createTime the value for gc_member_bank.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.flag_enable
     *
     * @return the value of gc_member_bank.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.flag_enable
     *
     * @param flagEnable the value for gc_member_bank.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.bank_verify
     *
     * @return the value of gc_member_bank.bank_verify
     *
     * @mbggenerated
     */
    public String getBankVerify() {
        return bankVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.bank_verify
     *
     * @param bankVerify the value for gc_member_bank.bank_verify
     *
     * @mbggenerated
     */
    public void setBankVerify(String bankVerify) {
        this.bankVerify = bankVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.delete_time
     *
     * @return the value of gc_member_bank.delete_time
     *
     * @mbggenerated
     */
    public String getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.delete_time
     *
     * @param deleteTime the value for gc_member_bank.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(String deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.sort_num
     *
     * @return the value of gc_member_bank.sort_num
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.sort_num
     *
     * @param sortNum the value for gc_member_bank.sort_num
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.card_kind
     *
     * @return the value of gc_member_bank.card_kind
     *
     * @mbggenerated
     */
    public String getCardKind() {
        return cardKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.card_kind
     *
     * @param cardKind the value for gc_member_bank.card_kind
     *
     * @mbggenerated
     */
    public void setCardKind(String cardKind) {
        this.cardKind = cardKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gc_member_bank.bank_icon_uid
     *
     * @return the value of gc_member_bank.bank_icon_uid
     *
     * @mbggenerated
     */
    public String getBankIconUid() {
        return bankIconUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gc_member_bank.bank_icon_uid
     *
     * @param bankIconUid the value for gc_member_bank.bank_icon_uid
     *
     * @mbggenerated
     */
    public void setBankIconUid(String bankIconUid) {
        this.bankIconUid = bankIconUid;
    }
}